redis:
  image: redis
  container_name: cache
  expose:
    - 6379
auth:
  build: ./auth
  links:
    - redis
  ports:
    - 8001:8001
  environment:
    - REDIS_URL=redis://cache
    - NODE_ENV=development
    - PORT=8001
  command:
    sh -c 'npm i && node server.js'
travel-log:
  build: ./travel-log
  links:
    - redis
  ports:
    - 8002:8002
  environment:
    - REDIS_URL=redis://cache
    - NODE_ENV=development
    - PORT=8002
  command:
    sh -c 'npm i && node server.js'
